# Generated by Django 5.0.2 on 2024-04-11 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_author_book_customer_genre_order_orderitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
